steps:
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']
    id: 'install-dependencies'

  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching DATABASE_URL from Secret Manager..."
        DATABASE_URL=$(gcloud secrets versions access latest --secret=DATABASE_URL)
        echo "Running database migrations..."
        DATABASE_URL=$DATABASE_URL npx sequelize-cli db:migrate --config config/config.js
    secretEnv: ['DATABASE_URL']
    id: 'database-migration'
    env:
      - 'NODE_ENV=production'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    id: 'deploy-app-engine'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
