steps:
  # Step 1: Install dependencies
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']
    id: 'install-dependencies'

  # Step 2: Run Sequelize migrations with DATABASE_URL from Secret Manager
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching DATABASE_URL from Secret Manager..."
        export DATABASE_URL=$(gcloud secrets versions access latest --secret=DATABASE_URL)
        echo "Running database migrations..."
        npx sequelize-cli db:migrate --config config/config.js
    id: 'database-migration'
    env:
      - 'NODE_ENV=production'
    secretEnv: ['DATABASE_URL']

  # Step 3: Deploy to Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    id: 'deploy-app-engine'

availableSecrets:
  secretManager:
    - versionName: projects/client-information-481623/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
